# Generated by Django 4.2.29 on 2026-03-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_seed_hyrox_intense'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_plan',
            field=models.ForeignKey(blank=True, help_text='Currently active training plan for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='plans.plan'),
        ),
    ]
