# Generated by Django 4.2.29 on 2026-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_active_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
