# Generated by Django 4.2.29 on 2026-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_date_of_birth_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_bests',
            field=models.JSONField(blank=True, default=dict, help_text='Personal best records for exercises. Format: {exerciseId: {weight, sets, reps, date}}'),
        ),
    ]
