"""Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.environ.get(name)
    if not raw:
        return default
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-tld+u(a-$e%@_ud-7gin0hh%#+6jzunott&5&d7w0-c+mb)w8p',
)

# Local development defaults to debug. Production must set DJANGO_DEBUG=0.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# Allow local development from browser and LAN; production should set
# DJANGO_ALLOWED_HOSTS to the deployed domain list.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['*'] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    'rest_framework',
	    'accounts',
	    'exercises',
	    'plans',
	    'workouts',
	    'insights',
	    'challenges',
	    'community',
	    'achievements',
]

MIDDLEWARE = [
	    'django.middleware.security.SecurityMiddleware',
	    'core.middleware.SimpleCorsMiddleware',
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ENGINE = os.environ.get('DJANGO_DATABASE_ENGINE', 'django.db.backends.sqlite3')
if DATABASE_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': os.environ.get('DJANGO_DATABASE_NAME', ''),
            'USER': os.environ.get('DJANGO_DATABASE_USER', ''),
            'PASSWORD': os.environ.get('DJANGO_DATABASE_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DATABASE_HOST', ''),
            'PORT': os.environ.get('DJANGO_DATABASE_PORT', ''),
            'CONN_MAX_AGE': int(os.environ.get('DJANGO_DATABASE_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework configuration
REST_FRAMEWORK = {
	    'DEFAULT_PERMISSION_CLASSES': [
	        'rest_framework.permissions.AllowAny',
	    ],
	    'DEFAULT_AUTHENTICATION_CLASSES': [
	        'rest_framework_simplejwt.authentication.JWTAuthentication',
	        'rest_framework.authentication.SessionAuthentication',
	    ],
	    'DEFAULT_THROTTLE_CLASSES': [
	        'rest_framework.throttling.ScopedRateThrottle',
	    ],
	    'DEFAULT_THROTTLE_RATES': {
	        'auth_login': '20/min',
	        'auth_register': '10/min',
	        'auth_register_validate': '30/min',
	    },
	    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
	    'PAGE_SIZE': 20,
}


# SimpleJWT configuration
SIMPLE_JWT = {
	    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
	    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
	    'ROTATE_REFRESH_TOKENS': False,
	    'BLACKLIST_AFTER_ROTATION': False,
}


# External API keys
#
# Default: read from environment variable. This is safest for production.
EXERCISEDB_API_KEY = os.environ.get('EXERCISEDB_API_KEY', '')

# Optional override: local api_keys.py file.
#
# Create backend/core/api_keys.py (NOT committed to git), copy the contents of
# api_keys_example.py, and paste your real keys there. If present, that file
# will override the env-based default above for local development.
try:  # pragma: no cover - simple configuration wiring
	from .api_keys import EXERCISEDB_API_KEY as _EXERCISEDB_API_KEY
	if _EXERCISEDB_API_KEY:
		EXERCISEDB_API_KEY = _EXERCISEDB_API_KEY
except ImportError:
	pass
