# Generated by Django 4.2.29 on 2026-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.JSONField()),
                ('detail', models.JSONField()),
                ('unlock', models.JSONField()),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
