# Generated by Django 4.2.29 on 2026-05-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_communitygroup_active_challenge_title_and_more'),
        ('challenges', '0009_userchallengecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('requirement', models.CharField(max_length=260)),
                ('duration_days', models.PositiveSmallIntegerField(default=7)),
                ('eligible_workout_types', models.JSONField(blank=True, default=list)),
                ('eligible_body_parts', models.JSONField(blank=True, default=list)),
                ('minimum_duration', models.PositiveSmallIntegerField(default=20)),
                ('required_sessions', models.PositiveSmallIntegerField(default=3)),
                ('allowed_intensity', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('official', 'Official'), ('community', 'Community'), ('group', 'Group')], default='community', max_length=24)),
                ('is_official', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('badge_icon', models.CharField(blank=True, max_length=64)),
                ('reward_xp', models.PositiveIntegerField(default=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=24)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('trending_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_challenges', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_challenges', to='community.communitygroup')),
            ],
            options={
                'ordering': ['-trending_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallengeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('left', 'Left')], default='active', max_length=24)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='challenges.trainingchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_challenge_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_completed', models.PositiveSmallIntegerField(default=0)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveSmallIntegerField(default=0)),
                ('qualifying_workout_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='challenges.userchallengeenrollment')),
            ],
            options={
                'ordering': ['-points', '-sessions_completed', 'updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userchallengeenrollment',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_c9f949_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeenrollment',
            index=models.Index(fields=['challenge', 'status'], name='challenges__challen_510ec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeenrollment',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='trainingchallenge',
            index=models.Index(fields=['status', 'visibility'], name='challenges__status_8642af_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingchallenge',
            index=models.Index(fields=['start_date', 'end_date'], name='challenges__start_d_21ad54_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingchallenge',
            index=models.Index(fields=['group', 'status'], name='challenges__group_i_c36e13_idx'),
        ),
    ]
