# Generated by Django 4.2.29 on 2026-03-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=16)),
                ('duration_weeks', models.PositiveSmallIntegerField()),
                ('goal', models.TextField()),
                ('summary', models.TextField()),
                ('audience', models.TextField()),
                ('result', models.TextField()),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=7)),
                ('long_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('focus', models.CharField(max_length=255)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'number'],
                'unique_together': {('plan', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField(help_text='Absolute day index in the plan (e.g. 1-21).')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text="Free-form duration label like '75 min' or 'Race'.", max_length=32)),
                ('day_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('recovery', 'Recovery'), ('mixed', 'Mixed')], max_length=16)),
                ('workout_template_id', models.SlugField(blank=True, help_text='Optional link to a WorkoutTemplate ID.', max_length=128)),
                ('nutrition', models.JSONField(blank=True, default=dict)),
                ('supplements', models.JSONField(blank=True, default=dict)),
                ('plan_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='plans.planweek')),
            ],
            options={
                'ordering': ['plan_week__plan_id', 'day_index'],
                'unique_together': {('plan_week', 'day_index')},
            },
        ),
    ]
