# Generated by Django 4.2.29 on 2026-03-28 11:02

from django.db import migrations


def seed_hyrox_intense(apps, schema_editor):
	Plan = apps.get_model('plans', 'Plan')
	PlanWeek = apps.get_model('plans', 'PlanWeek')
	PlanDay = apps.get_model('plans', 'PlanDay')

	plan, _ = Plan.objects.get_or_create(
		id='hyrox_intense_3wk',
		defaults={
			'name': 'Hyrox Intense (3-Week Race Prep)',
			'level': 'advanced',
			'duration_weeks': 3,
			'goal': 'A 3-week Hyrox race preparation program built on concurrent training with running and all 8 stations in the same sessions.',
			'summary': 'Three focused weeks that combine race-pace running, station technique, strength, recovery, and race simulations.',
			'audience': 'Intermediate to advanced athletes preparing for their first or next Hyrox race.',
			'result': 'By the end of 3 weeks you will have completed half and full race simulations, dialled in pacing and transitions, and rehearsed race-day nutrition.',
			'sessions_per_week': 7,
			'long_description': 'Three-week Hyrox race preparation plan built on concurrent training: running plus all race stations in the same sessions, with detailed recovery, nutrition, and supplement guidance.',
		},
	)

	# Week 1 — Build the Engine
	w1, _ = PlanWeek.objects.get_or_create(
		plan=plan,
		number=1,
		defaults={
			'title': 'Build the Engine',
			'focus': 'Build aerobic base, master all 8 station techniques, and establish pacing.',
			'highlights': [
				'Learn all 8 Hyrox stations at low intensity with hybrid station plus easy run sessions.',
				'Build aerobic base with easy and tempo runs plus a long run on tired legs.',
				'Use mobility and recovery days to protect joints, hips, and grip.',
			],
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=1,
		defaults={
			'title': 'Hybrid: Station Intro + Easy Run',
			'description': 'Low-intensity practice of all 8 stations, then 20 min easy run and cooldown stretching.',
			'duration': '75 min',
			'day_type': 'cardio',
			'nutrition': {
				'calories': '2000-2200',
				'protein_g': 150,
				'carbs_g': 200,
				'fat_g': 75,
				'notes': 'Balanced meals. Extra protein for repair. Hydrate 3-4L.',
			},
			'supplements': {
				'protocol': 'Vitamin D3, Omega3, Magnesium, Zinc, Ashwagandha 600mg, Tart Cherry Juice 60ml',
			},
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=2,
		defaults={
			'title': 'Strength: Push + Pull + Core',
			'description': 'Full-body strength for squat, row, overhead press, RDL, push-ups, carries, holds, and core, plus foam roll cooldown.',
			'duration': '60 min',
			'day_type': 'strength',
			'nutrition': {
				'calories': '2200-2400',
				'protein_g': 160,
				'carbs_g': 210,
				'fat_g': 75,
				'notes': 'Slightly higher carbs and protein to support strength session.',
			},
			'supplements': {
				'protocol': 'Vitamin D3, Omega3, Magnesium, Zinc, Creatine 5g',
			},
		},
	)

	# For brevity, seed the remaining days with lighter metadata; they can be
	# fully edited and enriched via the Django admin.
	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=3,
		defaults={
			'title': 'Hybrid: Tempo Run + Station Conditioning',
			'description': 'Tempo run blocks plus Hyrox sampler rounds (run, SkiErg, wall balls, row, burpee broad jumps).',
			'duration': '70 min',
			'day_type': 'cardio',
			'nutrition': {
				'calories': '2200-2400',
				'notes': 'Fuel for mixed tempo and station work; carbs around training window.',
			},
			'supplements': {
				'protocol': 'Vitamin D3, Omega3, Magnesium, Zinc',
			},
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=4,
		defaults={
			'title': 'Active Recovery + Mobility',
			'description': 'Easy walk or cycle plus long hip and thoracic mobility and grip care.',
			'duration': '40 min',
			'day_type': 'recovery',
			'nutrition': {
				'calories': '2000-2200',
				'notes': 'Lighter day with focus on anti-inflammatory foods and hydration.',
			},
			'supplements': {
				'protocol': 'Magnesium, Omega3, Zinc',
			},
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=5,
		defaults={
			'title': 'Station Strength: Sled + Carry + Lunge',
			'description': 'Heavy sled push and pull, long carries, sandbag lunges, accessories and core.',
			'duration': '65 min',
			'day_type': 'strength',
			'nutrition': {
				'calories': '2300-2500',
				'notes': 'Higher carbs and sodium to support heavy lower-body work.',
			},
			'supplements': {
				'protocol': 'Creatine 5g, Vitamin D3, Omega3, Magnesium, Zinc',
			},
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=6,
		defaults={
			'title': 'Long Run + Station Finisher',
			'description': '40 min easy run followed by station finisher (wall balls, SkiErg, burpee broad jumps, row).',
			'duration': '75 min',
			'day_type': 'cardio',
			'nutrition': {
				'calories': '2300-2500',
				'notes': 'Prioritize carbs pre- and post-run for glycogen.',
			},
			'supplements': {
				'protocol': 'Vitamin D3, Omega3, Magnesium, Zinc',
			},
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w1,
		day_index=7,
		defaults={
			'title': 'Full Rest Day',
			'description': 'Full rest with optional light walk, foam rolling, stretching, and extra sleep.',
			'duration': '0 min',
			'day_type': 'recovery',
			'nutrition': {
				'calories': '2000-2200',
				'notes': 'Focus on recovery foods, hydration, and sleep.',
			},
			'supplements': {
				'protocol': 'Magnesium, Omega3',
			},
		},
	)

	# Week 2 — Race Pace & Power (skeleton)
	w2, _ = PlanWeek.objects.get_or_create(
		plan=plan,
		number=2,
		defaults={
			'title': 'Race Pace & Power',
			'focus': 'Race pace intervals, heavier stations, back-to-back combos.',
			'highlights': [
				'Run 1 km race-pace intervals before heavy sled and station combos.',
				'Use heavy full-body strength to build power for sleds, carries, and lunges.',
				'Complete a half Hyrox race simulation to test pacing and transitions.',
			],
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=8,
		defaults={
			'title': 'Hybrid: Race Pace Intervals + Stations',
			'description': 'Warm up, 1 km race-pace intervals, then sled push and pull station combos on fatigued legs.',
			'duration': '80 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=9,
		defaults={
			'title': 'Heavy Strength: Full Body Power',
			'description': 'Heavy squats, deadlifts, pull-ups, push press, lunges, hip thrusts, carries and core.',
			'duration': '60 min',
			'day_type': 'strength',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=10,
		defaults={
			'title': 'Hybrid: Threshold Run + SkiErg/Row',
			'description': 'Threshold run plus SkiErg and rowing intervals with race-pace runs between.',
			'duration': '70 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=11,
		defaults={
			'title': 'Active Recovery + Mobility',
			'description': 'Very easy walk or cycle plus hip mobility, foam rolling, and forearm care.',
			'duration': '40 min',
			'day_type': 'recovery',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=12,
		defaults={
			'title': 'Station Power: Wall Balls + Burpees + Row',
			'description': 'High-volume wall balls, burpee broad jumps, rowing and SkiErg intervals plus strength finisher.',
			'duration': '65 min',
			'day_type': 'strength',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=13,
		defaults={
			'title': 'HALF RACE SIMULATION',
			'description': 'Half Hyrox simulation with repeated 1 km runs and key stations at race weight.',
			'duration': '90 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w2,
		day_index=14,
		defaults={
			'title': 'Full Rest Day',
			'description': 'Full rest day after half simulation with optional easy walk and recovery work.',
			'duration': '0 min',
			'day_type': 'recovery',
		},
	)

	# Week 3 — Sharpen & Peak (skeleton)
	w3, _ = PlanWeek.objects.get_or_create(
		plan=plan,
		number=3,
		defaults={
			'title': 'Sharpen & Peak',
			'focus': 'Volume drops, intensity stays. Full race simulation and taper.',
			'highlights': [
				'Sharp race-pace intervals with reduced strength volume.',
				'Full Hyrox race simulation mid-week.',
				'Structured taper into race day.',
			],
		},
	)

	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=15,
		defaults={
			'title': 'Hybrid: Sharp Intervals + Station Combos',
			'description': '800 m sharp intervals at race effort plus SkiErg, wall balls, and race-pace runs.',
			'duration': '70 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=16,
		defaults={
			'title': 'Maintenance Strength (Reduced Volume)',
			'description': 'Reduced-volume strength session to keep tension without fatigue.',
			'duration': '50 min',
			'day_type': 'strength',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=17,
		defaults={
			'title': 'FULL RACE SIMULATION',
			'description': 'Full Hyrox race simulation with all 8 runs and stations at race effort.',
			'duration': '100-120 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=18,
		defaults={
			'title': 'Full Rest — Post Simulation Recovery',
			'description': 'Complete recovery day after full simulation with walk, foam rolling, and bath.',
			'duration': '0 min',
			'day_type': 'recovery',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=19,
		defaults={
			'title': 'Taper: Easy Shakeout + Light Stations',
			'description': 'Easy shakeout run with very light station touches and mobility.',
			'duration': '45 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=20,
		defaults={
			'title': 'Pre-Race Day: Activation + Race Prep',
			'description': 'Short activation session plus race logistics checks and visualization.',
			'duration': '30 min',
			'day_type': 'cardio',
		},
	)
	PlanDay.objects.get_or_create(
		plan_week=w3,
		day_index=21,
		defaults={
			'title': 'RACE DAY',
			'description': 'Race day with morning routine, warm up, full Hyrox effort, and post-race recovery.',
			'duration': 'Race',
			'day_type': 'cardio',
		},
	)


class Migration(migrations.Migration):

	    dependencies = [
	        ('plans', '0001_initial'),
	    ]

	    operations = [
	        migrations.RunPython(seed_hyrox_intense, migrations.RunPython.noop),
	    ]
