# Generated by Django 4.2.29 on 2026-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_seed_hyrox_intense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planday',
            name='description',
            field=models.TextField(blank=True, help_text='Coach notes / long-form description of the session.'),
        ),
        migrations.CreateModel(
            name='PlanDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(help_text='Name of the block/exercise, e.g. "Barbell Deadlift" or "Warm Up".', max_length=255)),
                ('primary', models.CharField(blank=True, help_text='Primary prescription, e.g. "3 × 3" or "10 min".', max_length=255)),
                ('secondary', models.CharField(blank=True, help_text='Optional secondary detail, e.g. "80% 1RM" or "Easy pace".', max_length=255)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plans.planday')),
            ],
            options={
                'ordering': ['plan_day', 'order', 'id'],
            },
        ),
    ]
