# Generated by Django 4.2.29 on 2026-05-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_userplan_training_days_pattern'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userscheduledworkout',
            new_name='plans_users_user_pl_d3ad6a_idx',
            old_name='plans_users_user_pl_d8d5b6_idx',
        ),
        migrations.RenameIndex(
            model_name='userscheduledworkout',
            new_name='plans_users_schedul_ab314e_idx',
            old_name='plans_users_schedul_41f0ab_idx',
        ),
    ]
