from django.urls import path

from .views import (
	ActivityFeedView,
	ActivityCommentsView,
	ActivityLikeView,
	ActivityShareView,
	AddFriendView,
	CommunitySummaryView,
	CommunityOverviewView,
	ContactSyncView,
	FollowView,
	FriendListView,
	GroupChallengesView,
	GroupAnnouncementsView,
	GroupActivityPostView,
	GroupDetailView,
	GroupInviteView,
	GroupJoinRequestActionView,
	GroupJoinLeaveView,
	GroupLeaderboardView,
	GroupListCreateView,
	GroupMembersView,
	GroupRemoveMemberView,
	LeaderboardView,
	RemoveFriendView,
	TodayActivityView,
	UserSearchView,
)


urlpatterns = [
	path('community/summary/', CommunitySummaryView.as_view(), name='community-summary'),
	path('community/overview/', CommunityOverviewView.as_view(), name='community-overview'),
	path('community/friends/', FriendListView.as_view(), name='community-friends'),
	path('community/friends/add/', AddFriendView.as_view(), name='community-add-friend'),
	path('community/friends/<int:user_id>/', RemoveFriendView.as_view(), name='community-remove-friend'),
	path('community/search/', UserSearchView.as_view(), name='community-search'),
	path('community/contacts/sync/', ContactSyncView.as_view(), name='community-contact-sync'),
	path('community/leaderboard/', LeaderboardView.as_view(), name='community-leaderboard'),
	path('community/today-activity/', TodayActivityView.as_view(), name='community-today-activity'),
	path('community/activity/', ActivityFeedView.as_view(), name='community-activity'),
	path('community/activity/<int:activity_id>/like/', ActivityLikeView.as_view(), name='community-activity-like'),
	path('community/activity/<int:activity_id>/comments/', ActivityCommentsView.as_view(), name='community-activity-comments'),
	path('community/activity/<int:activity_id>/share/', ActivityShareView.as_view(), name='community-activity-share'),
	path('community/groups/', GroupListCreateView.as_view(), name='community-groups'),
	path('community/groups/<int:group_id>/', GroupDetailView.as_view(), name='community-group-detail'),
	path('community/groups/<int:group_id>/members/', GroupMembersView.as_view(), name='community-group-members'),
	path('community/groups/<int:group_id>/invite/', GroupInviteView.as_view(), name='community-group-invite'),
	path('community/groups/<int:group_id>/requests/<int:invite_id>/<str:action>/', GroupJoinRequestActionView.as_view(), name='community-group-request-action'),
	path('community/groups/<int:group_id>/remove-member/', GroupRemoveMemberView.as_view(), name='community-group-remove-member'),
	path('community/groups/<int:group_id>/challenges/', GroupChallengesView.as_view(), name='community-group-challenges'),
	path('community/groups/<int:group_id>/announcements/', GroupAnnouncementsView.as_view(), name='community-group-announcements'),
	path('community/groups/<int:group_id>/activity/', GroupActivityPostView.as_view(), name='community-group-activity'),
	path('community/groups/<int:group_id>/leaderboard/', GroupLeaderboardView.as_view(), name='community-group-leaderboard'),
	path('community/groups/<int:group_id>/<str:action>/', GroupJoinLeaveView.as_view(), name='community-group-action'),
	path('profiles/<int:user_id>/follow/', FollowView.as_view(), name='profile-follow'),
]
