# Generated by Django 4.2.29 on 2026-05-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('badge_earned', 'Badge earned'), ('level_up', 'Level up'), ('rank_moved', 'Rank moved'), ('challenge_almost_complete', 'Challenge almost complete'), ('group_goal_close', 'Group goal close'), ('monthly_badge_near_unlock', 'Monthly badge near unlock'), ('weekly_top_10_opportunity', 'Weekly top 10 opportunity'), ('plan_completion_milestone', 'Plan completion milestone')], max_length=48)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.SlugField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('consistency', 'Consistency'), ('pr', 'PR'), ('challenge', 'Challenge'), ('leaderboard', 'Leaderboard'), ('monthly', 'Monthly'), ('plan', 'Plan completion'), ('group', 'Group'), ('body_focus', 'Body focus'), ('comeback', 'Comeback'), ('special_event', 'Special event')], max_length=32)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('elite', 'Elite')], default='bronze', max_length=24)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('elite', 'Elite'), ('legendary', 'Legendary')], default='common', max_length=24)),
                ('unlock_description', models.CharField(blank=True, max_length=500)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('is_periodic', models.BooleanField(default=False)),
                ('display_priority', models.PositiveIntegerField(default=100)),
                ('shareable_card_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('workout_saved', 'Workout saved'), ('challenge_completed', 'Challenge completed'), ('plan_completed', 'Plan completed'), ('weekly_period_closed', 'Weekly period closed'), ('monthly_period_closed', 'Monthly period closed'), ('quarterly_period_closed', 'Quarterly period closed'), ('group_event', 'Group event'), ('pr_detected', 'PR detected')], max_length=40)),
                ('condition_type', models.CharField(max_length=80)),
                ('threshold', models.FloatField(default=1)),
                ('period', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('conditioning', 'Conditioning'), ('mobility', 'Mobility'), ('sport', 'Sport'), ('consistency', 'Consistency')], max_length=32)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(default='bronze', max_length=24)),
                ('next_tier_xp', models.PositiveIntegerField(default=1500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=16)),
                ('period_key', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='closed', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'type'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('current_title', models.CharField(default='Rookie', max_length=32)),
                ('current_level_xp', models.PositiveIntegerField(default=0)),
                ('next_level_xp', models.PositiveIntegerField(default=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_level', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('period_key', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_rows', to='achievements.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0)),
                ('percentile', models.FloatField(default=0)),
                ('awarded_badges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='achievements.leaderboardperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.AddIndex(
            model_name='leaderboardperiod',
            index=models.Index(fields=['type', 'status', 'start_date'], name='achievement_type_d9585f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardperiod',
            unique_together={('type', 'period_key')},
        ),
        migrations.AddField(
            model_name='featuredbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredbadge',
            name='user_badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_rows', to='achievements.userbadge'),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgerule',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='achievements.badge'),
        ),
        migrations.AddField(
            model_name='achievementevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'earned_at'], name='achievement_user_id_a288ed_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge', 'earned_at'], name='achievement_badge_i_1a3e91_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['period_key'], name='achievement_period__df3a0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge', 'period_key')},
        ),
        migrations.AddIndex(
            model_name='leaderboardresult',
            index=models.Index(fields=['period', 'rank'], name='achievement_period__619bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardresult',
            index=models.Index(fields=['user', 'rank'], name='achievement_user_id_a1a8a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardresult',
            unique_together={('period', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='featuredbadge',
            unique_together={('user', 'user_badge'), ('user', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='categorylevel',
            unique_together={('user', 'category')},
        ),
        migrations.AddIndex(
            model_name='badgerule',
            index=models.Index(fields=['trigger_type', 'condition_type'], name='achievement_trigger_de9c93_idx'),
        ),
        migrations.AddIndex(
            model_name='badgerule',
            index=models.Index(fields=['badge', 'trigger_type'], name='achievement_badge_i_9a79e2_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementevent',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='achievement_user_id_0ba2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementevent',
            index=models.Index(fields=['user', 'is_read'], name='achievement_user_id_6e12d7_idx'),
        ),
    ]
