# Generated by Django 4.2.29 on 2026-03-30 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_years', models.PositiveSmallIntegerField(help_text='Age in years at the time of the assessment.')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender at time of assessment.', max_length=16)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters at time of assessment.', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kilograms at time of assessment.', null=True)),
                ('waist_cm', models.FloatField(blank=True, help_text='Waist circumference in centimeters at time of assessment.', null=True)),
                ('resting_heart_rate', models.PositiveSmallIntegerField(help_text='Resting heart rate in beats per minute (bpm).')),
                ('max_pushups', models.PositiveSmallIntegerField(help_text='Maximum push-ups in one continuous set.')),
                ('max_run_minutes', models.PositiveSmallIntegerField(help_text='How many minutes the user can run without stopping.')),
                ('can_touch_toes', models.CharField(choices=[('yes', 'Yes'), ('almost', 'Almost'), ('no', 'No')], help_text='Self-reported flexibility test result.', max_length=8)),
                ('sleep_hours', models.FloatField(help_text='Average hours of sleep per night.')),
                ('source', models.CharField(blank=True, help_text='Optional label such as "onboarding" or "retest".', max_length=32)),
                ('tested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this assessment record was created.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
