# Generated by Django 4.2.29 on 2026-03-30 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_userplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_1km_seconds', models.PositiveIntegerField(help_text='Time to complete 1km run, in seconds.')),
                ('wall_balls_unbroken', models.PositiveSmallIntegerField(help_text='Max wall balls in one unbroken set.')),
                ('sled_difficulty', models.PositiveSmallIntegerField(help_text='Perceived sled difficulty on a 1-5 scale (5 = very hard).')),
                ('energy_level', models.PositiveSmallIntegerField(help_text='Self-reported energy level on a 1-5 scale.')),
                ('is_initial', models.BooleanField(default=False, help_text='Marks the initial Day 1 benchmark for this user-plan.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_benchmarks', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_benchmarks', to=settings.AUTH_USER_MODEL)),
                ('user_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_benchmarks', to='plans.userplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='insights_ra_user_id_98adaa_idx'), models.Index(fields=['user_plan', 'created_at'], name='insights_ra_user_pl_499b55_idx')],
            },
        ),
    ]
