# Generated by Django 4.2.29 on 2026-03-30 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0002_racebenchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('fitness_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentile_rank_overall', models.FloatField(blank=True, null=True)),
                ('race_readiness_score', models.FloatField(blank=True, null=True)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('streak_multiplier', models.FloatField(blank=True, null=True)),
                ('total_minutes_7d', models.PositiveIntegerField(default=0)),
                ('total_minutes_30d', models.PositiveIntegerField(default=0)),
                ('total_minutes_all_time', models.PositiveIntegerField(default=0)),
                ('body_balance_score', models.FloatField(blank=True, null=True)),
                ('fitness_age_detail', models.JSONField(blank=True, default=dict)),
                ('percentile_detail', models.JSONField(blank=True, default=dict)),
                ('race_readiness_detail', models.JSONField(blank=True, default=dict)),
                ('streak_detail', models.JSONField(blank=True, default=dict)),
                ('total_time_detail', models.JSONField(blank=True, default=dict)),
                ('body_battle_map_detail', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User metrics snapshot',
                'verbose_name_plural': 'User metrics snapshots',
            },
        ),
    ]
