# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_usermetricssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessassessment',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender at time of assessment.', max_length=24),
        ),
    ]
