# Generated by Django 4.2.29 on 2026-03-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0005_userplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_tune_demo_exercises_for_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_template_id', models.SlugField(blank=True, help_text='Identifier of the WorkoutTemplate this session is based on.', max_length=128)),
                ('planned_week_number', models.PositiveSmallIntegerField(blank=True, help_text='Denormalised week number within the plan for analytics.', null=True)),
                ('planned_day_key', models.CharField(blank=True, help_text="Identifier for the plan day (e.g. 'w1_mon').", max_length=32)),
                ('quick_workout_id', models.SlugField(blank=True, help_text='Optional ID for quick workouts not tied to a plan.', max_length=128)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the user started this session.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this session.', null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Total duration of the workout in minutes.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra data (e.g. RPE summary, device IDs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='plans.userplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_prescribed', models.PositiveSmallIntegerField(blank=True, help_text='Sets prescribed for this exercise, copied from template.', null=True)),
                ('reps_prescribed', models.PositiveSmallIntegerField(blank=True, help_text='Reps prescribed per set, copied from template.', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this exercise was marked complete, if applicable.', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['session', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status'], name='workouts_wo_user_id_8a43bb_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'completed_at'], name='workouts_wo_user_id_90b8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['plan', 'user_plan'], name='workouts_wo_plan_id_3a98b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexercise',
            unique_together={('session', 'exercise')},
        ),
    ]
