# Generated by Django 4.2.29 on 2026-05-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_profile', models.CharField(choices=[('gym', 'Gym'), ('cardio', 'Cardio'), ('hybrid', 'Hybrid')], default='hybrid', max_length=16)),
                ('weekly_workouts_target', models.PositiveSmallIntegerField(default=4)),
                ('active_days_target', models.PositiveSmallIntegerField(default=4)),
                ('custom_targets', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScorePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rolling_30', 'Rolling 30 days')], max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('activity_xp', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('challenge_score', models.FloatField(default=0)),
                ('balance_bonus', models.FloatField(default=0)),
                ('leaderboard_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('monthly_xp', models.PositiveIntegerField(default=0)),
                ('career_xp', models.PositiveIntegerField(default=0)),
                ('performance_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('training_balance_score', models.FloatField(default=0)),
                ('challenge_score', models.FloatField(default=0)),
                ('strength_score', models.FloatField(default=0)),
                ('cardio_score', models.FloatField(default=0)),
                ('conditioning_score', models.FloatField(default=0)),
                ('mobility_score', models.FloatField(default=0)),
                ('sport_score', models.FloatField(default=0)),
                ('recovery_score', models.FloatField(default=0)),
                ('upper_body_score', models.FloatField(default=0)),
                ('lower_body_score', models.FloatField(default=0)),
                ('core_score', models.FloatField(default=0)),
                ('push_score', models.FloatField(default=0)),
                ('pull_score', models.FloatField(default=0)),
                ('legs_score', models.FloatField(default=0)),
                ('full_body_score', models.FloatField(default=0)),
                ('body_part_scores', models.JSONField(blank=True, default=dict)),
                ('manual_log_count', models.PositiveIntegerField(default=0)),
                ('recorded_log_count', models.PositiveIntegerField(default=0)),
                ('active_days_count', models.PositiveIntegerField(default=0)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(default='Rookie', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_xp', models.PositiveIntegerField(default=0)),
                ('leaderboard_xp', models.PositiveIntegerField(default=0)),
                ('challenge_points', models.PositiveIntegerField(default=0)),
                ('base_score', models.FloatField(default=0)),
                ('duration_multiplier', models.FloatField(default=1)),
                ('intensity_multiplier', models.FloatField(default=1)),
                ('type_multiplier', models.FloatField(default=1)),
                ('trust_multiplier', models.FloatField(default=1)),
                ('completion_bonus', models.FloatField(default=0)),
                ('detail_bonus', models.FloatField(default=0)),
                ('anti_spam_modifier', models.FloatField(default=1)),
                ('overtraining_modifier', models.FloatField(default=1)),
                ('calculation_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='body_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='entry_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('recorded_timer', 'Recorded timer'), ('plan_workout', 'Plan workout'), ('challenge_workout', 'Challenge workout')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='focus_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='intensity',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pr_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='recorded_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='trust_level',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('conditioning', 'Conditioning'), ('mobility', 'Mobility'), ('sport', 'Sport'), ('recovery', 'Recovery'), ('custom', 'Custom')], default='custom', max_length=32),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'entry_source', 'completed_at'], name='workouts_wo_user_id_89f914_idx'),
        ),
        migrations.AddField(
            model_name='workoutscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_record', to='workouts.workoutsession'),
        ),
        migrations.AddField(
            model_name='workoutdraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscoresummary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscoreperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workoutdraft',
            index=models.Index(fields=['user', 'updated_at'], name='workouts_wo_user_id_91cd68_idx'),
        ),
        migrations.AddIndex(
            model_name='userscoreperiod',
            index=models.Index(fields=['period_type', 'period_start', 'leaderboard_score'], name='workouts_us_period__95c52c_idx'),
        ),
        migrations.AddIndex(
            model_name='userscoreperiod',
            index=models.Index(fields=['user', 'period_type'], name='workouts_us_user_id_19dff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userscoreperiod',
            unique_together={('user', 'period_type', 'period_start', 'period_end')},
        ),
    ]
