# Generated by Django 4.2.29 on 2026-05-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_userpubliccard_overall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('challenge_type', models.CharField(default='custom', max_length=64)),
                ('eligible_workout_types', models.JSONField(blank=True, default=list)),
                ('eligible_body_parts', models.JSONField(blank=True, default=list)),
                ('min_duration', models.PositiveSmallIntegerField(default=20)),
                ('max_daily_entries', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scoring_rules', models.JSONField(blank=True, default=dict)),
                ('completion_bonus', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('recorded_workouts', models.PositiveIntegerField(default=0)),
                ('manual_logs', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-points', '-active_days', '-recorded_workouts', 'manual_logs', 'completed_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='communityactivity',
            new_name='community_c_user_id_1e4006_idx',
            old_name='community_c_user_id_d1dc28_idx',
        ),
        migrations.RenameIndex(
            model_name='communityactivity',
            new_name='community_c_activit_dd6a64_idx',
            old_name='community_c_activit_430a2e_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='community_f_from_us_ec484e_idx',
            old_name='community_f_from_us_9cc3f9_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='community_f_to_user_88ce2c_idx',
            old_name='community_f_to_user_a9cfb5_idx',
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='performance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='tier',
            field=models.CharField(default='Rookie', max_length=32),
        ),
        migrations.AddField(
            model_name='userpubliccard',
            name='weekly_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchallengeprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='community.groupchallenge'),
        ),
        migrations.AddField(
            model_name='groupchallengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_community_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityshare',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='community.communityactivity'),
        ),
        migrations.AddField(
            model_name='activityshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylike',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communityactivity'),
        ),
        migrations.AddField(
            model_name='activitylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communityactivity'),
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', 'status'], name='community_u_followe_b610d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following', 'status'], name='community_u_followi_ef9e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'status'], name='community_g_group_i_841095_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'status'], name='community_g_user_id_fff3e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupinvite',
            index=models.Index(fields=['group', 'status'], name='community_g_group_i_27e22c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvite',
            index=models.Index(fields=['invitee', 'status'], name='community_g_invitee_8d0527_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('group', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='groupchallengeprogress',
            index=models.Index(fields=['challenge', 'points'], name='community_g_challen_fc8aa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchallengeprogress',
            unique_together={('challenge', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupchallenge',
            index=models.Index(fields=['group', 'start_date', 'end_date'], name='community_g_group_i_e88f47_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['privacy', 'updated_at'], name='community_c_privacy_f83750_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['owner', 'updated_at'], name='community_c_owner_i_6780c8_idx'),
        ),
        migrations.AddIndex(
            model_name='activityshare',
            index=models.Index(fields=['activity', 'created_at'], name='community_a_activit_b118ea_idx'),
        ),
        migrations.AddIndex(
            model_name='activityshare',
            index=models.Index(fields=['user', 'created_at'], name='community_a_user_id_2f8e94_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylike',
            index=models.Index(fields=['activity', 'created_at'], name='community_a_activit_ccbf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylike',
            index=models.Index(fields=['user', 'created_at'], name='community_a_user_id_611b55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitylike',
            unique_together={('activity', 'user')},
        ),
        migrations.AddIndex(
            model_name='activitycomment',
            index=models.Index(fields=['activity', 'created_at'], name='community_a_activit_fddb48_idx'),
        ),
    ]
