# Generated by Django 4.2.29 on 2026-05-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_activitycomment_activitylike_activityshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='active_challenge_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='goal',
            field=models.CharField(choices=[('competitive', 'Competitive'), ('accountability', 'Accountability'), ('casual', 'Casual'), ('event_prep', 'Event prep'), ('transformation', 'Transformation')], default='accountability', max_length=32),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='group_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='group_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('running', 'Running'), ('hybrid', 'Hybrid'), ('office', 'Office'), ('college', 'College'), ('sports', 'Sports'), ('recovery', 'Recovery'), ('open', 'Open')], default='open', max_length=32),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='weekly_activity_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='weekly_goal_target',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='badge_icon',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='required_sessions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='reward_xp',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='groupchallenge',
            name='visibility',
            field=models.CharField(default='group', max_length=32),
        ),
        migrations.AlterField(
            model_name='communityactivity',
            name='activity_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('challenge', 'Challenge'), ('plan', 'Plan'), ('test', 'Fitness test'), ('badge', 'Badge'), ('group', 'Group')], max_length=24),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite only')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16),
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('workout_event', 'Workout event'), ('challenge_update', 'Challenge update'), ('milestone', 'Milestone'), ('celebration', 'Celebration'), ('admin_note', 'Admin note')], default='admin_note', max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(blank=True, max_length=700)),
                ('is_pinned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_announcements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='community.communitygroup')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['group', 'is_pinned', 'created_at'], name='community_g_group_i_af3669_idx')],
            },
        ),
    ]
