# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('community', '0004_communitygroup_active_challenge_title_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='groupchallengeprogress',
			name='qualifying_workout_ids',
			field=models.JSONField(blank=True, default=list),
		),
	]
