# Generated by Django 4.2.29 on 2026-06-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_groupchallengeprogress_qualifying_workout_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='community.communityactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at', '-id'], name='community_a_user_id_2ff7fa_idx'), models.Index(fields=['activity', 'created_at'], name='community_a_activit_30a94a_idx')],
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
