# Generated by Django 4.2.29 on 2026-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_activitysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpubliccard',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
