# Generated by Django 4.2.29 on 2026-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], max_length=16)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('movement_pattern', models.CharField(max_length=64)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('is_compound', models.BooleanField(default=True)),
                ('video_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('primary_muscles', models.ManyToManyField(related_name='primary_exercises', to='exercises.musclegroup')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
