# Generated by Django 4.2.29 on 2026-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_musclegroup_canonical_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, help_text='High-level body part from external APIs (e.g. chest, back, cardio).', max_length=64),
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, default=list, help_text='Step-by-step instructions; list of strings.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_targets',
            field=models.JSONField(blank=True, default=list, help_text='Secondary target muscles from external APIs.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source',
            field=models.CharField(default='internal', help_text='Origin of this exercise definition, e.g. internal|exercisedb.', max_length=32),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.CharField(blank=True, help_text='Primary target muscle or system from external APIs.', max_length=128),
        ),
    ]
